# Generated by Django 2.0.7 on 2020-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=15, null=True)),
                ('emailid', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
    ]
