# Generated by Django 2.0.7 on 2020-10-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
