# Generated by Django 2.0.7 on 2020-10-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcontact', '0002_auto_20201025_0652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
