# Generated by Django 2.0.7 on 2020-10-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcontact', '0003_auto_20201025_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False},
        ),
    ]
