# Generated by Django 2.0.7 on 2020-10-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcontact', '0004_auto_20201025_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True},
        ),
    ]
