# Generated by Django 2.0.7 on 2020-10-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcontact', '0005_auto_20201025_0658'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
